openapi: "3.0.0"
info:
  version: 1.0.0
  title: MongoDB Content Search
servers:
  - url: https://rag-chatgpt-plugin.vercel.app
paths:
  /api/content:
    get:
      summary: Get content search results
      operationId: getContent
      parameters:
        - name: q
          in: query
          description: A query to search for what the user wants. include frontmatter on top of the query featuring the relevant programming language and product, if relevant. See example.
          example: |
            ---
            product: Drivers
            programmingLanguage: Python
            ---
            how to add data to mongodb with the python driver?
          required: true
          schema:
            type: string
